FROM debian:10.8-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y curl unzip git hub && apt-get clean && rm -rf /var/lib/apt/lists/* && \
    curl -s https://releases.hashicorp.com/terraform/0.14.5/terraform_0.14.5_linux_amd64.zip -o terraform.zip && \
    unzip terraform.zip && mv terraform /usr/bin
