FROM alpine:3.13

RUN wget https://releases.hashicorp.com/terraform/0.14.5/terraform_0.14.5_linux_amd64.zip && \
    unzip terraform_0.14.5_linux_amd64.zip && mv terraform /usr/bin && \
    apk add --update --no-cache bash openssh libc6-compat git && \
    wget https://github.com/github/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz -O hub.tgz && \
    mkdir /hub && tar -xvf hub.tgz -C /hub --strip-components 1 && alias git=hub && \
    bash /hub/install && rm -rf /hub hub.tgz
